from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

CPPPATH += ['RTT/']
src 	= ['RTT/osal.c']

group = DefineGroup('soem-osal', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
