from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

CPPPATH += ['RTT/', '../soem']
src 	= ['RTT/oshw.c', 'RTT/nicdrv.c', 'RTT/net.c']

group = DefineGroup('soem-oshw', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
