from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

CPPPATH += ['../soem']
src 	= ['RTT/slaveinfo/slaveinfo.c']

group = DefineGroup('soem-test', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
