from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]
CPPPATH += ['../oshw/RTT']
CPPPATH += ['../osal']
CPPPATH += ['../osal/RTT']

group = DefineGroup('soem', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
